# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(471, 431)
        MainWindow.setStyleSheet("background-color: #2e2e2e;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 121, 531))
        self.frame.setStyleSheet("background-color: #000000;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.openFile = QtWidgets.QPushButton(self.frame)
        self.openFile.setGeometry(QtCore.QRect(10, 120, 101, 61))
        font = QtGui.QFont()
        font.setFamily("mr_ApexMk3")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.openFile.setFont(font)
        self.openFile.setStyleSheet("QPushButton {\n"
"    background-color: #000000;\n"
"    border: 2px solid #8600ad;\n"
"    border-radius: 30;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #8600ad;\n"
"}")
        self.openFile.setObjectName("openFile")
        self.openDiagram = QtWidgets.QPushButton(self.frame)
        self.openDiagram.setGeometry(QtCore.QRect(10, 200, 101, 61))
        font = QtGui.QFont()
        font.setFamily("mr_ApexMk3")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.openDiagram.setFont(font)
        self.openDiagram.setStyleSheet("QPushButton {\n"
"    background-color: #000000;\n"
"    border: 2px solid #8600ad;\n"
"    border-radius: 30;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #8600ad;\n"
"}")
        self.openDiagram.setObjectName("openDiagram")
        self.viewFile = QtWidgets.QPushButton(self.frame)
        self.viewFile.setGeometry(QtCore.QRect(10, 280, 101, 61))
        font = QtGui.QFont()
        font.setFamily("mr_ApexMk3")
        font.setPointSize(9)
        self.viewFile.setFont(font)
        self.viewFile.setStyleSheet("QPushButton {\n"
"    background-color: #000000;\n"
"    border: 2px solid #8600ad;\n"
"    border-radius: 30;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #8600ad;\n"
"}")
        self.viewFile.setObjectName("viewFile")
        self.downloadFile = QtWidgets.QPushButton(self.frame)
        self.downloadFile.setGeometry(QtCore.QRect(10, 360, 101, 61))
        font = QtGui.QFont()
        font.setFamily("mr_ApexMk3")
        font.setPointSize(9)
        self.downloadFile.setFont(font)
        self.downloadFile.setStyleSheet("QPushButton {\n"
"    background-color: #000000;\n"
"    border: 2px solid #8600ad;\n"
"    border-radius: 30;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #8600ad;\n"
"}")
        self.downloadFile.setObjectName("downloadFile")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 511, 101))
        self.frame_2.setStyleSheet("background-color: #000000;\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.text_json = QtWidgets.QLabel(self.frame_2)
        self.text_json.setGeometry(QtCore.QRect(160, 0, 251, 91))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.text_json.setFont(font)
        self.text_json.setStyleSheet("color: white;")
        self.text_json.setObjectName("text_json")
        self.picJson = QtWidgets.QLabel(self.frame_2)
        self.picJson.setGeometry(QtCore.QRect(30, 20, 71, 71))
        self.picJson.setText("")
        self.picJson.setPixmap(QtGui.QPixmap("1.png"))
        self.picJson.setScaledContents(True)
        self.picJson.setObjectName("picJson")
        self.diagram_ = QtWidgets.QLabel(self.centralwidget)
        self.diagram_.setGeometry(QtCore.QRect(120, 100, 351, 331))
        self.diagram_.setStyleSheet("border: 4px solid #8600ad;\n"
"")
        self.diagram_.setText("")
        self.diagram_.setScaledContents(True)
        self.diagram_.setAlignment(QtCore.Qt.AlignCenter)
        self.diagram_.setObjectName("diagram_")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.openFile.setText(_translate("MainWindow", "Load JSON"))
        self.openDiagram.setText(_translate("MainWindow", "JSON diagram"))
        self.viewFile.setText(_translate("MainWindow", "View JSON"))
        self.downloadFile.setText(_translate("MainWindow", "download"))
        self.text_json.setText(_translate("MainWindow", "J S O N"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
